spring.application.name=demo

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TESTDB;encrypt=false
spring.datasource.username=sa
spring.datasource.password=YourStrong!Passw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate / JPA configs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
#spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Location of log file
logging.file.name=logs/app.log

# Log level (set to DEBUG if you want detailed logs)
logging.level.root=INFO
logging.level.com.example.demo=DEBUG


